generators:
  'default':
    priority: 1
    blocks:
      - 'NETHERRACK;100'
  'donor':
    priority: 2
    blocks:
      - 'NETHERRACK;50'
      - 'DIRT;50'
generation_default_block: NETHERRACK
generation_check_time: 2 secs
generation_interval_time: 2 secs - 3 secs
source_permissions:
  - 'infinitelavasource.use'
source_wait_time: 2 secs
repeat_source_checks: true
enabled_worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'